---

# see directories.yml for similarly grouped items
- name: Render file from variable
  ansible.builtin.template:
    src: "{{ item.src | default('files/file.j2') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  loop: "{{ files }}"
  become: "{{ item.become | default(false) }}"
  no_log: "{{ item.no_log | default(omit) }}"
  when:
    - files is defined
    - files | length > 0
    - item.content is defined
  tags:
    - files
