# SPDX-License-Identifier: MIT-0
---

- name: Base
  ansible.builtin.import_tasks:
    file: base.yml

- name: System controls
  ansible.builtin.import_tasks:
    file: sysctl.yml

- name: Directories
  ansible.builtin.import_tasks:
    file: files.yml

- name: Files
  ansible.builtin.import_tasks:
    file: files.yml
