# SPDX-License-Identifier: MIT-0
---
- name: Set up /etc/sysctl.d configs
  ansible.builtin.template:
    dest: "/etc/sysctl.d/{{ item.name }}"
    src: sysctl/sysctl.conf
    mode: "0644"
  when:
    - sysctl is defined
  loop: "{{ (sysctl | default([])) + sysctl_extra }}"
  become: true
  tags:
    - sysctl

- name: Run propagate sysctl settings
  ansible.builtin.import_tasks:
    file: sysctlpropagate.yml
  when:
    - sysctl is defined
  tags:
    - sysctl
